### ISSUE TITLE
doesn't mount the swapfile

### ISSUE THREAD

**Issue by roumano** [robertdebock/ansible-role-swap#3]
## Describe the bug
the role create the good configuration in the `/etc/fstab` but it's didn't mount it

## Playbook

```yaml
- name: test swap
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: robertdebock.swap
      swap_files:
        - path: /swapfle
          size: 2048

```

## Output

```
TASK [swap : Mount swap] *********************************************************************************************************************************************************************************************************************************************************************************************
task path: ...../ansible/roles/swap/tasks/main.yml:36

ok: [sql3] => (item={'path': '/swapfle', 'size': 2048}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "dump": "0",
    "fstab": "/etc/fstab",
    "fstype": "swap",
    "invocation": {
        "module_args": {
            "backup": false,
            "boot": true,
            "dump": "0",
            "fstab": null,
            "fstype": "swap",
            "opts": "sw",
            "passno": "0",
            "path": "none",
            "src": "/swapfle",
            "state": "present"
        }
    },
    "item": {
        "path": "/swapfle",
        "size": 2048
    },
    "name": "none",
    "opts": "sw",
    "passno": "0",
    "src": "/swapfle"
}
```

## Environment

- Control node OS: Ubuntu 22.04.1 LTS
- Control node Ansible version: 2.10.8
- Managed node OS: Debian GNU/Linux 10 (buster)

Looking at the documentation of ansible ( https://docs.ansible.com/ansible/latest/collections/ansible/posix/mount_module.html )

the actual state is not sufficient : 

| Parameter | Comments | 
| -- | -- |
| state string / required | If mounted, the device will be actively mounted and appropriately configured in fstab. If the mount point is not present, the mount point will be created. If unmounted, the device will be unmounted without changing fstab. present only specifies that the device is to be configured in fstab and does not trigger or require a mount. absent specifies that the device mount’s entry will be removed from fstab and will also unmount the device and remove the mount point. remounted  specifies that the device will be remounted for when you want to force a  refresh on the mount itself (added in 2.9). This will always return  changed=true. If opts is set, the options will be applied to the remount, but will not change fstab.  Additionally, if opts is set, and the remount command fails, the module will error to prevent unexpected mount changes.  Try using mounted instead to work around this issue. Choices:  absent mounted present unmounted remounted |

So idealy `state: present` should be replace by `state: mounted` but on this case the role is crashing : 
```
TASK [swap : Mount swap] *********************************************************************************************************************************************************************************************************************************************************************************************
failed: [xxx] (item={'path': '/swapfle', 'size': 2048}) => {"ansible_loop_var": "item", "changed": false, "item": {"path": "/swapfle", "size": 2048}, "msg": "Error mounting none: mount: /root/none: unknown filesystem type 'swap'.\n"}
```
So maybe it's need a longer fix ...

**Comment by robertdebock** [comment]
Fixed in [version 2.1.4](https://github.com/robertdebock/ansible-role-swap/releases/tag/2.1.4). Please let me know if this helps you.
